
package lab1.generate.client;

import lab1.country.Country;
import lab1.country.CountryWebService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.jws.WebService;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(endpointInterface = "lab1.generate.client.CountryWebService")
@WebServiceClient(name = "CountryWebserviceImplService", targetNamespace = "http://country.lab1/", wsdlLocation = "http://localhost:8081/ws/country?wsdl")
public class CountryWebserviceImplService
        extends Service implements lab1.country.CountryWebService
{

    private final static URL COUNTRYWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException COUNTRYWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName COUNTRYWEBSERVICEIMPLSERVICE_QNAME = new QName("http://country.lab1/", "CountryWebserviceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            // url = new URL("http://localhost:8081/ws/country?wsdl");
            url = new URL(null, "http://localhost:8081/ws/country?wsdl", new sun.net.www.protocol.http.Handler());
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COUNTRYWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        COUNTRYWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CountryWebserviceImplService() {
        super(__getWsdlLocation(), COUNTRYWEBSERVICEIMPLSERVICE_QNAME);
    }

    public CountryWebserviceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COUNTRYWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public CountryWebserviceImplService(URL wsdlLocation) {
        super(wsdlLocation, COUNTRYWEBSERVICEIMPLSERVICE_QNAME);
    }

    public CountryWebserviceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COUNTRYWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public CountryWebserviceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CountryWebserviceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CountryWebService
     */
    @WebEndpoint(name = "CountryWebserviceImplPort")
    public lab1.country.CountryWebService getCountryWebserviceImplPort() {
        return super.getPort(new QName("http://country.lab1/", "CountryWebserviceImplPort"), lab1.country.CountryWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CountryWebService
     */
    @WebEndpoint(name = "CountryWebserviceImplPort")
    public lab1.country.CountryWebService getCountryWebserviceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://country.lab1/", "CountryWebserviceImplPort"), CountryWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COUNTRYWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw COUNTRYWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return COUNTRYWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }



    @Override
    public Country getCountryById(int arg0)
    {
        return null;
    }

    @Override
    public boolean updateCountry(Country arg0)
    {
        return false;
    }

    @Override
    public Country[] getAllCountries()
    {
        return new Country[0];
    }

    @Override
    public boolean removeCountryById(int arg0)
    {
        return false;
    }
}
