
package lab1.country;

import lab1.generate_client.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CountryWebService", targetNamespace = "http://country.lab1/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CountryWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns lab1.country.Country
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://country.lab1/CountryWebService/getCountryByIdRequest", output = "http://country.lab1/CountryWebService/getCountryByIdResponse")
    public Country getCountryById(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @return
     *     returns lab1.country.CountryArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://country.lab1/CountryWebService/getAllCountriesRequest", output = "http://country.lab1/CountryWebService/getAllCountriesResponse")
    public Country[] getAllCountries();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://country.lab1/CountryWebService/updateCountryRequest", output = "http://country.lab1/CountryWebService/updateCountryResponse")
    public boolean updateCountry(
        @WebParam(name = "arg0", partName = "arg0")
        Country arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://country.lab1/CountryWebService/removeCountryByIdRequest", output = "http://country.lab1/CountryWebService/removeCountryByIdResponse")
    public boolean removeCountryById(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

}
